import type { Metadata } from "next";
import "./globals.css";
import { Menu } from "@/components";
import { ThemeProvider } from "next-themes";
import { getMenu } from "@/services/get-menu";
import { MenuItemProps } from "@/components/menu/menu.type";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items: MenuItemProps[] = await getMenu();

  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          enableSystem={true}
          defaultTheme="dark"
          storageKey="theme"
        >
          <Menu data={items} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
